version: "3"
services:
  bitbucket:
    image: atlassian/bitbucket-server:latest
    ports:
      - 7990:7990
      - 7999:7999
    volumes:
      - bitbucketVolume:/var/atlassian/application-data/bitbucket
volumes:
  bitbucketVolume:
